// Utility script to sort savedata into grouped objects
var kd = require('kd-tree-javascript');
const stars = [
    {star:"Sierra",x:-2200,z:3500},
    {star:"Aries",x:-3500,z:2000},
    {star:"Talison",x:100,z:2000},
    {star:"Cygnus",x:-1700,z:1250},
    {star:"Fauston",x:-500,z:800},
    {star:"Cerulean",x:2400,z:2100},
    {star:"Onyx",x:3500,z:1000},
    {star:"Olympus Prime",x:1250,z:500},
    {star:"Sapphire",x:0,z:0},
    {star:"Lambda",x:-1250,z:-400},
    {star:"Emerald",x:-3200,z:-550},
    {star:"Rigel",x:-3200,z:-2500},
    {star:"Sirius",x:-2300,z:-3700},
    {star:"Orion",x:-1000,z:-2400},
    {star:"Thuban",x:0,z:-500},
    {star:"Virgo",x:700,z:-1250},
    {star:"Pices",x:1800,z:-300},
    {star:"Pearl",x:3500,z:-1800},
    {star:"Rucker",x:1800,z:-2000},
    {star:"Aquila",x:1400,z:-2700},
    {star:"Alpha Centauri",x:1300,z:-3700},
    {star:"Deneb",x:3500,z:-3500},
    {star:"Sol",x:-1050,z:-5050}
];

const points = stars.map(function (p) {
    return {x: p.x, z: p.z}
});

var distance = function(a, b){
    return Math.pow(a.x - b.x, 2) +  Math.pow(a.z - b.z, 2);
  }

var tree = new kd.kdTree(points, distance, ["x", "z"]);

var nearest = (sx, sz) =>{
        
    var near = tree.nearest({ x: parseInt(sx), z: parseInt(sz) }, 1)[0][0];
    let filtered = stars.filter((star) => {
        return (star.x == near.x) && (star.z == near.z);
    });    
    return filtered[0].star;
};


exports.sorted = function(d) {
    var closest_gate = nearest(d.player_position_SX, d.player_position_SZ);
    var gamedata = {
        "player": {
            "pilot_name":d.pilot_name,
            "fuel":d.fuel,
            "cash":d.cash,
            "closest_gate": closest_gate,
            "local_planet_name":d.local_planet_name,
            "player_position_X":d.player_position_X,
            "player_position_Y":d.player_position_Y,
            "player_position_Z":d.player_position_Z,
            "player_position_SX":d.player_position_SX,
            "player_position_SY":d.player_position_SY,
            "player_position_SZ":d.player_position_SZ,
            "total_kills":d.total_kills,
            "total_contracts":d.total_contracts,
            "skill_and_proficiency_rating":d.skill_and_proficiency_rating,
            "military_rank":d.military_rank
        },
        "contracts": {
            "current_contract_type":d.current_contract_type,
            "current_contract_pay_amount":d.current_contract_pay_amount
        },
        "ship": {
            "ship_type":d.ship_type,
            "engine_class":d.engine_class,
            "shield_class":d.shield_class,
            "player_ship_velocity":d.player_ship_velocity,
            "player_ship_set_velocity":d.player_ship_set_velocity,
            "player_ship_altitude":d.player_ship_altitude,
            "gravity_level":d.gravity_level,
            "heat_signature_level":d.heat_signature_level,
            "player_ship_total_velocity":d.player_ship_total_velocity,
            "player_ship_heading":d.player_ship_heading,
            "cargo_capacity":d.cargo_capacity,
            "wing_and_thruster_class":d.wing_and_thruster_class,
            "crew_limit":d.crew_limit,
            "equipment_limit":d.equipment_limit,
            "countermeasure_limit":d.countermeasure_limit,
            "countermeasures_remaining":d.countermeasures_remaining,
            "hardpoint_limit":d.hardpoint_limit,
            "armor_limit":d.armor_limit,
            "energy_level":d.energy_level,
            "energy_bias_setting":d.energy_bias_setting,
            "front_shield_level":d.front_shield_level,
            "right_shield_level":d.right_shield_level,
            "left_shield_level":d.left_shield_level,
            "rear_shield_level":d.rear_shield_level,
            "hull_damage_level":d.hull_damage_level,
            "engine_damage":d.engine_damage,
            "weapon_damage":d.weapon_damage,
            "nav_damage":d.nav_damage,
            "equipment_slot_1":d.equipment_slot_1,
            "equipment_slot_2":d.equipment_slot_2,
            "equipment_slot_3":d.equipment_slot_3,
            "equipment_slot_4":d.equipment_slot_4,
            "equipment_slot_5":d.equipment_slot_5,
            "equipment_slot_6":d.equipment_slot_6,
            "equipment_slot_7":d.equipment_slot_7,
            "equipment_slot_8":d.equipment_slot_8,
            "equipment_slot_9":d.equipment_slot_9,
            "equipment_slot_10":d.equipment_slot_10,
            "secondary_weapon_slot_1":d.secondary_weapon_slot_1,
            "secondary_weapon_slot_2":d.secondary_weapon_slot_2,
            "secondary_weapon_slot_3":d.secondary_weapon_slot_3,
            "secondary_weapon_slot_4":d.secondary_weapon_slot_4,
            "secondary_weapon_slot_5":d.secondary_weapon_slot_5,
            "secondary_weapon_slot_6":d.secondary_weapon_slot_6,
            "secondary_weapon_slot_7":d.secondary_weapon_slot_7,
            "secondary_weapon_slot_8":d.secondary_weapon_slot_8,
            "cargo_bay_1":d.cargo_bay_1,
            "cargo_bay_2":d.cargo_bay_2,
            "cargo_bay_3":d.cargo_bay_3,
            "cargo_bay_4":d.cargo_bay_4,
            "cargo_bay_5":d.cargo_bay_5,
            "cargo_bay_6":d.cargo_bay_6,
            "cargo_bay_7":d.cargo_bay_7,
            "cargo_bay_8":d.cargo_bay_8,
            "cargo_bay_9":d.cargo_bay_9,
            "cargo_bay_10":d.cargo_bay_10,
            "IDS_status":d.IDS_status,
            "IDS_multiplier":d.IDS_multiplier,
            "afterburner_status":d.afterburner_status,
            "autopilot_status":d.autopilot_status,
            "navigation_console_status":d.navigation_console_status,
            "build_console_status":d.build_console_status,
            "inventory_console_status":d.inventory_console_status,
            "trade_console_status":d.trade_console_status,
            "tractor_beam_status":d.tractor_beam_status,
            "HUD_status":d.HUD_status,
            "target_display_status":d.target_display_status,
            "jump_drive_status":d.jump_drive_status,
            "jump_drive_delay_time":d.jump_drive_delay_time
        },
        "sector": {
            "local_planet_name":d.local_planet_name,
            "closest_gate": closest_gate,
            "player_position_SX":d.player_position_SX,
            "player_position_SY":d.player_position_SY,
            "player_position_SZ":d.player_position_SZ,
            "station_in_sector":d.station_in_sector,
            "carrier_in_sector":d.carrier_in_sector,
            "jump_gate_in_sector":d.jump_gate_in_sector,
            "planet_in_sector":d.planet_in_sector,
            "gase_planet_in_sector":d.gase_planet_in_sector,
            "moon_in_sector":d.moon_in_sector,
            "star_in_sector":d.star_in_sector,
            "asteroid_field_in_sector":d.asteroid_field_in_sector,
            "cave_in_sector":d.cave_in_sector,
            "nebula_cloud_in_sector":d.nebula_cloud_in_sector,
            "wormhole_in_sector":d.wormhole_in_sector,
            "blackhole_in_sector":d.blackhole_in_sector,
            "comet_in_sector":d.comet_in_sector,
            "nav_destination_sector_distance":d.nav_destination_sector_distance
        },
        "econ": {
            "local_planet_name":d.local_planet_name,
            "closest_gate": closest_gate,
            "player_position_SX":d.player_position_SX,
            "player_position_SY":d.player_position_SY,
            "player_position_SZ":d.player_position_SZ,
            "regional_economy_level":d.regional_economy_level,
            "regional_territory_control":d.regional_territory_control,
            "station_attack_status":d.station_attack_status,
            "region_index_value":d.region_index_value,
            "food_price":d.food_price,
            "medical_supplies_price":d.medical_supplies_price,
            "hydrogen_price":d.hydrogen_price,
            "electronics_price":d.electronics_price,
            "solar_price":d.solar_price,
            "metal_price":d.metal_price,
            "diamond_price":d.diamond_price,
            "antimatter_price":d.antimatter_price,
            "fusion_price":d.fusion_price,
            "machinery_price":d.machinery_price,
            "textiles_price":d.textiles_price,
            "platinum_price":d.platinum_price,
            "biological_price":d.biological_price,
            "oxygen_price":d.oxygen_price,
            "gold_price":d.gold_price,
            "silver_price":d.silver_price,
            "water_price":d.water_price,
            "armor_price":d.armor_price
        },
        "target": {
            "target_description":d.target_description,
            "target_threat_level":d.target_threat_level,
            "target_range":d.target_range,
            "target_front_shield_level":d.target_front_shield_level,
            "target_right_shield_level":d.target_right_shield_level,
            "target_left_shield_level":d.target_left_shield_level,
            "target_rear_shield_level":d.target_rear_shield_level,
            "target_engine_damage":d.target_engine_damage,
            "target_weapon_damage":d.target_weapon_damage,
            "target_nav_damage":d.target_nav_damage,
            "capital_ship_weapon_turret_1":d.capital_ship_weapon_turret_1,
            "capital_ship_weapon_turret_2":d.capital_ship_weapon_turret_2,
            "capital_ship_weapon_turret_3":d.capital_ship_weapon_turret_3,
            "capital_ship_weapon_turret_4":d.capital_ship_weapon_turret_4,
            "target_cargo_bay_1":d.target_cargo_bay_1,
            "target_cargo_bay_2":d.target_cargo_bay_2,
            "target_cargo_bay_3":d.target_cargo_bay_3,
            "target_cargo_bay_4":d.target_cargo_bay_4,
            "target_cargo_bay_5":d.target_cargo_bay_5,
            "target_cargo_bay_6":d.target_cargo_bay_6,
            "target_cargo_bay_7":d.target_cargo_bay_7,
            "target_cargo_bay_8":d.target_cargo_bay_8,
            "target_cargo_bay_9":d.target_cargo_bay_9,
            "target_cargo_bay_10":d.target_cargo_bay_10,
            "inbound_missile_alert":d.inbound_missile_alert,
            "particle_cannon":d.particle_cannon,
            "beam_cannon":d.beam_cannon,
            "particle_cannon_range":d.particle_cannon_range,
            "armed_missile_range":d.armed_missile_range,
            "targeted_subsystem":d.targeted_subsystem,
            "target_faction":d.target_faction,
            "target_damage_level":d.target_damage_level,
            "target_velocity":d.target_velocity,
            "target_engine_class_or_object_contents_1":d.target_engine_class_or_object_contents_1,
            "target_resistor_packs_or_object_contents_2":d.target_resistor_packs_or_object_contents_2,
            "target_hull_plating_or_object_contents_3":d.target_hull_plating_or_object_contents_3,
            "target_module_type_or_object_contents_4":d.target_module_type_or_object_contents_4,
            "target_wing_class_or_object_contents_5":d.target_wing_class_or_object_contents_5
        }
    }
    return gamedata;
};